package org.apache.bigtop.manager.common.utils;

import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.io.FileWriter;
import java.io.IOException;
import java.util.Iterator;
import java.util.Map;
import java.util.Properties;
import java.util.Set;

@Slf4j
@Component
public class PropertiesUtils {

    public boolean createProperties(String fileName, Map<String, Object> map) {
        boolean flag = false;
        if (fileName == null) {
            return flag;
        } else {
            String line = System.getProperty("line.separator");

            StringBuffer sb = new StringBuffer();
            sb.append("# Generated by Apache BigTop Manager.").append(line);
            FileWriter fw = null;
            try {
                fw = new FileWriter(fileName, false);

                for (Map.Entry<String, Object> entry : map.entrySet()) {
                    sb.append(entry.getKey() + "=" + entry.getValue()).append(line);
                }
                fw.write(sb.toString());

                flag = true;
            } catch (IOException e) {

            } finally {
                try {
                    if (fw != null) {
                        fw.close();
                    }
                } catch (IOException ignore) {
                }
                return flag;
            }
        }
    }
}
