bigtop:
  manager:
    server:
      host: localhost
      port: 8080

spring:
  application:
    name: bigtop-manager-agent

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    enable:
      jvm: false
      logback: false
      executor: false
      process: false
      tomcat: false
      http: false
      system: false
      disk: false
      application: false
