bigtop:
  manager:
    server:
      host: localhost
      port: 8080

spring:
  banner:
    charset: utf-8
  application:
    name: bigtop-manager-agent

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        web:
          socket: DEBUG
